name: Pre-Deployment Workflow (Docker Scout)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pre-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t arlethl/scout-cli:latest .

      # Ejecutar Docker Scout CVE Analysis
      - name: Run Docker Scout CVE Analysis
        uses: docker/scout-action@v1
        with:
          image: arlethl/checklistctpat:latest  # Repositorio de Docker Hub
          command: cves
          only-severities: critical,high
          exit-code: true

      - name: Run Docker Scout Recommendations
        uses: docker/scout-action@v1
        with:
          image: arlethl/scout-cli:latest
          command: recommendations
          only-severities: critical,high
          exit-code: true

      - name: Evaluate Security Policies with Docker Scout
        uses: docker/scout-action@v1
        with:
          image: arlethl/scout-cli:latest
          command: policy
          exit-code: true

      # AutenticaciÃ³n para Docker Hub
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Usando el secreto de Docker Hub
          password: ${{ secrets.DOCKER_TOKEN }}  # Usando el token de Docker Hub

      - name: Push Docker image to Docker Hub
        run: docker push arlethl/scout-cli:latest

      - name: Export CVEs to JSON and upload as artifact
        run: docker scout cves arlethl/scout-cli:latest --output json > cves.json

      - name: Upload CVEs report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cves-report
          path: cves.json
